language: swift
osx_image: xcode8.3
script:
- xcodebuild -project IGZLocation.xcodeproj -scheme IGZLocation -destination "platform=iOS
  Simulator,name=iPhone 7,OS=10.3" -configuration Debug -enableCodeCoverage YES clean
  build test
after_success:
- bash <(curl -s https://codecov.io/bash)